spring:
  application:
    name: micro-service-colors
---
server:
  port: 8080

spring:
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
      hibernate.temp.use_jdbc_metadata_defaults: false
      hibernate.jdbc.lob.non_contextual_creation: true
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://35.196.189.46:5432/multiplica?useSSL=false&autoReconnect=true
    username: postgres
    password: nNkp7LFvcnnGFmEk
    hikari:
      maximum-pool-size: "${DATABASE_POOL_SIZE:5}"
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        socketTimeout: 6
      idle-timeout: "${IDLE_TIMEOUT:300000}"
      connection-test-query: SELECT 1
      connection-timeout: "${CONNECTION_TIMEOUT:500}"
      minimum-idle: "${MINIMUM_IDLE:1}"